### ISSUE TITLE
Unable to patch Nexus 5X

### ISSUE THREAD

**Issue by poisonsnak** [ale5000-git/tingle#2]
I came from here https://github.com/moosd/Needle/issues/16 with the same issue.  Here are the two files you asked for: [boot-fw.zip](https://github.com/ale5000-git/tingle/files/440990/boot-fw.zip)

My device has /system/framework/arm/boat.oat as well as  /system/framework/arm64/boat.oat.  They are quite large (about 60MB) so I only included the first one as you requested but if you need the other let me know.  When I run your patch this is the output:

`$ sudo python3 patch.py`
`Where do you want to take the file to patch?`

`1 - From the device (adb)`
`2 - From the input folder`

`> 1`

`*** OS: Linux 4.6.0-1-amd64 (linux)`
`*** Selected device: 00defa40427cb549`
`*** Working dir: /tmp/tmp5pkyxhn2`
`*** Pulling framework from device...`
`6 KB/s (310 bytes in 0.043s)`
`*** Disassembling framework...`
`*** Disassembling classes...`
`Traceback (most recent call last):`
`File "patch.py", line 156, in <module>`
`smali_folder, dex_filename, dex_filename_last = find_smali(smali_to_search, "framework/");`
`File "patch.py", line 147, in find_smali`
`dir_list = tuple(sorted(os.listdir(dir)));`
`FileNotFoundError: [Errno 2] No such file or directory: 'framework/'`

I tried copying /system/framework/framework.jar to the input folder and running it again with option 2 but the result is the same.

Thanks for your hard work on this.  If you need anything else from me let me know.

**Comment by ale5000-git** [comment]
Thanks for the files :)

For now I have added the detection with a nicer message about the problem.
It will require some time to code it and I'm not sure if I will insert the code directly inside Tingle or if I will create a separate tool to run before Tingle.

I will write here when I have done some progress but do not expect something soon.
