### ISSUE TITLE
Unable to root adbd in TWRP 3.0.2 on Asus Z00AD (ZE551ML)

### ISSUE THREAD

**Issue by Bartvz** [ale5000-git/tingle#21]
As requested [here](https://github.com/ale5000-git/tingle/issues/15) a new issue.

When running "python main.py" in TWRP 3.0.2 recovery with the system partition mounted on an Asus Z00AD (ZE551ML), the process hangs indefenitely on "Rooting adbd"

*** Decompressing framework... DEBUG: Decompressing framework.jar *** Disassembling classes... DEBUG: Disassembling framework/classes.dex *** Patching... *** Detected: Android 7.x / Android 6.0.x / CyanogenMod 13-14 *** Patching succeeded. *** Reassembling classes... DEBUG: Assembling out/classes.dex *** Recompressing framework... DEBUG: Compressing framework.jar *** Copying the patched file to the output folder... *** Rooting adbd...

Pressing ctrl+c prints the following lines:
Traceback (most recent call last): File "main.py", line 522, in <module> enable_device_writing(chosen_one) File "main.py", line 214, in enable_device_writing File "main.py", line 210, in root_adbd subprocess.check_call([DEPS_PATH["adb"], "-s", chosen_device, "wait-for-device"]) File "C:\Users\Bart\AppData\Local\Programs\Python\Python35\lib\subprocess.py", line 581, in check_call raise CalledProcessError(retcode, cmd) subprocess.CalledProcessError: Command '['C:\\Users\\Bart\\AppData\\Local\\Android\\android-sdk\\platform-tools\\adb.exe', '-s', 'F5AZFG159469', 'wait-for-device']' returned non-zero exit status 3221225786

Running "adb -s device_name root" or  "adb -s device_name wait-for-device" from within unofficial CM14.1 or TWRP recovery doesn't print any lines. Running "adb -s device_name wait-for-device" in recovery makes the command prompt stall.

Hopefully I have provided enough information. In case I did not please let me know!

**Comment by valpackett** [comment]
Yeah, just encountered this as well, commenting out `subprocess.check_call([DEPS_PATH["adb"], "-s", chosen_device, "wait-for-device"])` makes everything work fine.

**Comment by ale5000-git** [comment]
@Bartvz @myfreeweb

I have fixed the problem, can you please try it and report back when you have time?
PS: The problem is fixed when running it under Python 3.3 or higher, on old versions it behave as before.
