### ISSUE TITLE
this patch not working for LG G2

### ISSUE THREAD

**Issue by eaglebooy** [ale5000-git/tingle#44]
Hi this is first time i hear about faking google signature
my phone is too slow with google apps ( playstore and playservices )
i really want to use this patch , i need this patch , i try many times but get this error

> MENU

    1 - Patch file from a device (adb)
    2 - Patch file from the input folder

> 2

 *** OS: Windows 10 (win)
 *** Python: 3.6.0 (64 bit)
 *** Mode: 2
 *** Working dir: C:\Users\MOHAMM~1\AppData\Local\Temp\Tingle-kod027kz
 *** Device SDK: 21
 *** Decompressing framework...
      DEBUG: Decompressing framework.jar
 *** Disassembling classes...
      DEBUG: Disassembling framework/classes.dex
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/jf/baksmali/Main : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)
Traceback (most recent call last):
  File "F:\ROMS\+sign spoof\tingle-master\main.py", line 598, in <module>
    smali_folder, dex_filename, dex_filename_last = find_smali(smali_to_search, "framework/", DEVICE_SDK)
  File "F:\ROMS\+sign spoof\tingle-master\main.py", line 516, in find_smali
    disassemble(search_dir+filename, out_dir, device_sdk)
  File "F:\ROMS\+sign spoof\tingle-master\main.py", line 483, in disassemble
    subprocess.check_call(disass_cmd)
  File "C:\Python36\lib\subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['C:\\Windows\\system32\\java.exe', '-jar', 'F:\\ROMS\\+sign spoof\\tingle-master/tools/baksmali.jar', 'dis', '-l', '--seq', '-o', './smali-classes/', 'framework/classes.dex', '-a', '21']' returned non-zero exit status 1.

here is files you need
[https://mega.nz/#!cAdGlKzA!JAdAvJ1Z674BFMCyXX0dT-BDG_uj-F_zguf_39rO46s](url)

thanks alot for your help , sorry for my english

**Comment by ale5000-git** [comment]
Hi,
are you sure you get the correct files?

1) It is possible that you haven't used an updated Tingle (you need to update all files, not just main.py)
2) build.prop come from Android 5 (SDK 21)
3) framework.jar come from Android 4.4 (SDK 19)

So what do this mean?
You need build.prop and framework.jar from the same device or you will get a broken file.

**Comment by eaglebooy** [comment]
thanks i will check it

**Comment by eaglebooy** [comment]
how to know sdk version of framework.jar?

**Comment by ale5000-git** [comment]
Tingle detect Android 4.4 (that correspond to SDK 19 in 99% of cases) from your framework.jar during the patching procedure.
