### ISSUE TITLE
FileNotFoundError: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by jakariyaa** [ale5000-git/tingle#49]
Tried in my Redmi4A (rolex) running on LineageOS 17.1 by yurikoles.

D:\Downloads\minimal_adb_fastboot_1.4.3_portable>python main.py
MENU

    1 - Patch file from a device (adb)
    2 - Patch file from the input folder

> 1

 *** OS: Windows 10 (win)
 *** Python: 3.8.3 (64 bit)
 *** Mode: 1
 *** Working dir: C:\Users\Zack\AppData\Local\Temp\Tingle-amtqi1eh
 *** Selected device: 1de4f5307d83
 *** Automounting /system...

ERROR INFO
==========
Type: <class 'FileNotFoundError'>
Name: The system cannot find the file specified (2)

Traceback (most recent call last):
  File "main.py", line 588, in <module>
    adb_automount_if_needed(SELECTED_DEVICE, "/system")
  File "main.py", line 327, in adb_automount_if_needed
    output = safe_subprocess_run([DEPS_PATH["adb"], "-s", chosen_device, "shell", "case $(mount) in  *' "+partition+" '*) echo 'Already mounted';;  *) mount '"+partition+"';;  esac"])
  File "main.py", line 204, in safe_subprocess_run
    return subprocess.check_output(command, stderr=subprocess.STDOUT)
  File "C:\Users\Zack\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Users\Zack\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\Zack\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Zack\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by JonnyTech** [comment]
Do you have `adb.exe` in your path? What happens if you type `adb` at the command prompt?

**Comment by jakariyaa** [comment]
Sorry I was using Minimal Portable ADB. This Error seemed to be fixed after installing full Adb 1.4.3 succesfully. But facing another issue now. :')
