### ISSUE TITLE
bad /etc/fstab

### ISSUE THREAD

**Issue by ghost** [ale5000-git/tingle#50]
Tried running this on Oneplus 6 (enchilada) w/ LineageOS 17.1

--

[me@me tingle-master]$ sudo python3 main.py
[sudo] password for me: 
MENU

    1 - Patch file from a device (adb)
    2 - Patch file from the input folder

> 1

 *** OS: Linux 5.6.19-2-MANJARO (linux)
 *** Python: 3.8.5 (64 bit)
 *** Mode: 1
 *** Working dir: /tmp/Tingle-j54jx9we
 *** Selected device: 4ceedc75
 *** Automounting /system...

ERROR INFO
==========
Type: <class 'subprocess.CalledProcessError'>
Cmd: ['/usr/bin/adb', '-s', '4ceedc75', 'shell', "case $(mount) in  *' /system '*) echo 'Already mounted';;  *) mount '/system';;  esac"]
Return code: 1
Output: mount: bad /etc/fstab: No such file or directory

Traceback (most recent call last):
  File "main.py", line 588, in <module>
    adb_automount_if_needed(SELECTED_DEVICE, "/system")
  File "main.py", line 327, in adb_automount_if_needed
    output = safe_subprocess_run([DEPS_PATH["adb"], "-s", chosen_device, "shell", "case $(mount) in  *' "+partition+" '*) echo 'Already mounted';;  *) mount '"+partition+"';;  esac"])
  File "main.py", line 204, in safe_subprocess_run
    return subprocess.check_output(command, stderr=subprocess.STDOUT)
  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/bin/adb', '-s', '4ceedc75', 'shell', "case $(mount) in  *' /system '*) echo 'Already mounted';;  *) mount '/system';;  esac"]' returned non-zero exit status 1.

**Comment by LnLcFlx** [comment]
+1

**Comment by becknik** [comment]
I noticed the same problem as you. Booting into recovery, mounting system partition and then running the script solved the problem for me. 
- Then I rebooted and I found my device bootlooping... Maybe you'll have more luck with your rom and device (using los 17.1 on an OnePlus 6t).
